name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Run Build and Test Workflow
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build and Test
      run: |
        set -e
        changedFiles=$(git diff --name-only HEAD~1 HEAD | grep '\.cpp$')

        # Find the solution directories
        solutionsToRun=""
        for file in $changedFiles; do
          if [[ $file == solutions/* ]]; then
            dir=$(dirname "$file")
            solutionsToRun="$solutionsToRun $dir"
          fi
        done

        # Remove duplicates
        solutionsToRun=($(echo "${solutionsToRun[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))

        if [ -z "$solutionsToRun" ]; then
          echo "No solutions to build or test. Exiting."
          exit 0
        fi

        echo "Solutions to process: ${solutionsToRun[@]}"
        for solution in "${solutionsToRun[@]}"; do
          ./build-and-test.sh "$solution"
        done
