name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Run Build and Test Workflow
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build and Test
      run: |
        set -e
        solutions=()

        # handle empty commit
        if git rev-parse HEAD~1 >/dev/null 2>&1; then
          changedFiles=$(git diff --name-only HEAD~1 HEAD | grep '\.cpp$')
        else
          echo "No previous commit to compare against. Assuming all .cpp are changed"
          changedFiles=$(find solutions -type f -name '*.cpp')
        fi

        # find the solution directories
        for file in $changedFiles; do
          if [[ $file == solutions/* ]]; then
            solution=$(echo $file | awk -F'/' '{print $2}')
            solutions+=("$solution")
          fi
        done

        # remove duplicates
        solutions=($(echo "${solutions[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))

        if [[ ${#solutions[@]} -eq 0 ]]; then
          echo "No solutions to build or test. Exiting."
          exit 0
        fi

        echo "Solutions to process: ${solutions[@]}"
        for solution in "${solutions[@]}"; do
          ./build-and-test.sh ${solution%.*}
        done
