name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Run script that builds and tests pushed solution
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build and Test
      run: |
        set -e
        changed_files=$(git diff --name-only HEAD~1 HEAD)

        # Find the solution(s) to build
        solutions_to_run=""
        for file in $changed_files; do
          case "$file" in
            solutions/*)
              solution=$(echo "$file" | cut -d'/' -f2)
              solutions_to_run="$solutions_to_run $solution"
              ;;
          esac
        done

        # Remove duplicates
        solutions_to_run=($(echo "${solutions_to_run[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))

        if [ -z "$solutions_to_run" ]; then
          echo "No solutions bound. Exiting now."
          exit 0
        fi

        echo "Solutions to build and test: $solutions_to_run"
        for solution in "${solutions_to_run[@]}"; do
          ./build-and-test.sh "$solution"
        done
